services:
    database:
        image: mongodb
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        networks:
            - app_network
    backend:
        image: #upload no dockerhub
        container_name: backend
        ports:
            - "5229:5229"
        networks:
            - app_network
        environment:
            MONGODB_URL: mongodb://mongodb:27017 
        depends_on:
            - database
    frontend:
        image: #upload no dockerhub
        container_name: frontend
        ports: 
        networks: 
        depends_on:
            - backend
volumes:
    mongodb_data:

networks:
    app_network:
        driver: bridge
