services:
  reverse:
    container_name: reverse
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl/private
    networks:
      - app_network
    depends_on:
      - frontend
      - backend

  database:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5229:8080"
    networks:
      - app_network
    environment:
      - CervejariaDatabase__ConnectionString=mongodb://database:27017
      - Redis__Configuration=redis:6379
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - database
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data

  frontend:
    image: gabrielcouzzi/frontendcervejaria:latest
    container_name: frontend
    ports: 
      - "8080:80"
    networks: 
      - app_network
    depends_on:
      - backend

volumes:
  mongodb_data:
  redis_data:

networks:
  app_network:
    driver: bridge
